---
abstract: 'use different context based on the request path'
author:
  - "Andreas 'ac0v' Specht <ac0v@sys-network.de>"
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Runtime: 5.8
  Catalyst::Test: 0
  Moose: 0
  Tie::Hash::NamedCapture: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-PathContext
provides:
  CatalystX::PathContext:
    file: lib/CatalystX/PathContext.pm
    version: v0.0.1
requires:
  Catalyst::Exception: 0
  Moose::Role: 0
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
